#!/bin/sh
# Sample simulator to Dakota system call script
# See Advanced Simulation Code Interfaces chapter in Users Manual

# $1 is params.in FROM Dakota
# $2 is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing ros.in
# Use the following line if SNL's APREPRO utility is used instead of DPrePro.
# ../aprepro -c '*' -q --nowarning ros.template ros.in

dprepro $1 sediment_sedbed_toy.template sediment_sedbed_toy.in

# --------
# ANALYSIS
# --------
pwd 
#cp -r ../casebase/* 

./coawstM > log.out

python util.py 
# ---------------
# POST-PROCESSING
# ---------------

# extract function value from the simulation output
#grep 'Function value' ros.out | cut -c 18- > results.tmp
# extract gradients from the simulation output (in this case will be ignored
# by DAKOTA if not needed)
#grep -i 'Function g' ros.out | cut -c 21- >> results.tmp
#mv results.tmp $2
